version: '3.9'

name: mariadb_test

services:

  db:
    container_name: ${PROJECT_NAME}_db
    hostname: ${PROJECT_NAME}_db
    image: mariadb:${MARIADB_VERSION}
    restart: ${MARIADB_OPTION_RESTART}
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

  adminer:
    container_name: ${PROJECT_NAME}_adminer
    hostname: ${PROJECT_NAME}_admin
    image: adminer:${ADMINER_VERSION}
    restart: ${ADMINER_OPTION_RESTART}
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ${ADMINER_DESIGN}